#!/bin/bash 
logdir="$WHERELOG/$(date -u +'%Y%m%d')"
if [ $# -eq 0 ];
  then filedisp="$logdir/human.log"
  else filedisp="$logdir/$1.log"
fi
tail -q -f $filedisp | sed -e "s/[0-9/]* /`printf "\033[33m"`/;s/\.[0-9]* [a-zA-Z0-9]* */`printf "\\033[0m - \\033[34m"`/;s/$/`printf "\\033[0m"`/"
