#!/bin/bash
# written by Guillaume Schworer, 2016

echo ""

old=$(ls ./*.rst | grep -v index.rst | wc -l)
if [ "$old" -ne 0 ]; then
    ls ./*.rst | grep -v index.rst | xargs rm
    echo "Removed $old old docs (.rst) files"
else
    echo "No old docs files found."
fi


#sphinx-apidoc -o ./ ../ctrl/ ../ctrl/test/ ../ctrl/c* ../ctrl/example*
sphinx-apidoc \
    -f -e --module-first --no-toc -o ./ ../ctrl/ \
    $(find ../ctrl/ -maxdepth 1 -mindepth 1 -type d) \
    $(find ../ctrl/ -maxdepth 1 -regextype posix-egrep \
        ! -regex ".*/telecommand.py|.*/telemetry.py|.*/__init__.py" -type f)

echo ""
echo "Created new docs (.rst) files"

make html
make latexpdf
echo ""
echo "Compiled into pdf and html"

cd ./_build/html/
zip -r -0 html.zip *
cd ../..
echo ""
echo "Created html tarball"

mkdir -p ./old_docs
mv ./PicSatHTML*.zip ./old_docs/
mv ./PicSat*.pdf ./old_docs/
echo ""
echo "Moved old documentation to ./old_docs/"

now="$(date +'%Y_%m_%dx%H_%M_%S')"
mv ./_build/html/html.zip "./PicSatHTML_$now.zip"
mv ./_build/latex/picsat.pdf "./PicSat_$now.pdf"
echo ""
echo "Copied latest documentation to root"

echo ""
echo "All done"
echo ""
